/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData settings = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData micOff = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ocr = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doubleBracket = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slash = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox1 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
